"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework', # Sẽ cần cho DRF
    'django.contrib.sites', # Cần thiết cho allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # Thêm Google provider
    'minio_storage',

    # Your apps
    'accounts',
    'documents',
]

# Cấu hình Site Framework (Bắt buộc cho Allauth, cần thiết cho django.contrib.sites)
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Thêm middleware của Allauth tại đây
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'DIRS': [config('BASE_DIR', 'templates')],  # Thêm thư mục templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='document_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='db'),
        'PORT': config('DB_PORT', default=5432, cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # Chuyển sang tiếng Việt: "vi-vn"

TIME_ZONE = config('TZ')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Cấu hình File tĩnh (Static Files) và File Media (Uploaded Files)
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User' # Thiết lập mô hình User tùy chỉnh

# Cấu hình Ký Số Nội Bộ
SIGNING_PRIVATE_KEY_PATH = config('SIGNING_PRIVATE_KEY_PATH')
SIGNING_PUBLIC_KEY_PATH = config('SIGNING_PUBLIC_KEY_PATH')

try:
    with open(SIGNING_PRIVATE_KEY_PATH, 'rb') as f:
        SIGNING_PRIVATE_KEY = f.read()
    with open(SIGNING_PUBLIC_KEY_PATH, 'rb') as f:
        SIGNING_PUBLIC_KEY_PEM = f.read().decode('utf-8')
except FileNotFoundError:
    print("WARNING: Signing keys not found. Internal signing will fail.")
    SIGNING_PRIVATE_KEY = None
    SIGNING_PUBLIC_KEY_PEM = None

# Cấu hình Celery/Redis
REDIS_HOST = config('REDIS_HOST', default='redis')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_PASSWORD = config('REDIS_PASSWORD')

# --- Celery Configuration (Dùng Redis làm Broker) ---
# Đảm bảo bạn đã định nghĩa REDIS_HOST và REDIS_PORT trong .env
# Redis là Message Broker cho Celery
REDIS_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0'

# Broker (Dùng cho Celery)
CELERY_BROKER_URL = REDIS_URL

# Backend (Dùng để lưu trữ kết quả của các tasks)
CELERY_RESULT_BACKEND = REDIS_URL

# Cho phép cả task và kết quả được mã hóa bằng JSON
CELERY_ACCEPT_CONTENT = ['json']

# Cấu hình Celery (Thêm vào khối CELERY_ trong settings.py)
# Đảm bảo Task được gửi/nhận bằng JSON (an toàn hơn pickle)
CELERY_TASK_SERIALIZER = 'json'

# Đảm bảo kết quả Task được lưu bằng JSON
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = TIME_ZONE  # Đồng bộ với múi giờ Django

CELERY_ENABLE_UTC = False

CELERY_BEAT_SCHEDULE = {
    # Ví dụ: Task kiểm tra hash toàn bộ file mỗi 24 giờ (Tùy chọn)
    'verify-all-hashes-daily': {
        'task': 'documents.tasks.verify_all_hashes',
        'schedule': 86400.0,  # 24 giờ * 3600 giây
        'args': (),
    },
}

# Cấu hình Allauth làm backend xác thực
AUTHENTICATION_BACKENDS = [
    # Bắt buộc cho Django Admin
    'django.contrib.auth.backends.ModelBackend',

    # Allauth cho social login
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Lấy biến môi trường từ .env
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')

# URL sau khi đăng nhập/đăng xuất thành công
LOGIN_REDIRECT_URL = '/' # Hoặc '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Cấu hình Google Social Provider
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # Cấu hình SCOPE và AUTH_PARAMS
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': GOOGLE_CLIENT_ID,
            'secret': GOOGLE_CLIENT_SECRET,
            'key': '', # Không dùng
        }
    }
}

# Cấu hình allauth
# Sử dụng email làm định danh chính
# 1. Thiết lập login/auth methods
ACCOUNT_LOGIN_METHODS = ['email'] # Dùng email thay vì username # {'email'}

# 2. Định nghĩa rõ ràng các trường đăng ký (Khắc phục Lỗi CRITICAL)
# Chỉ bao gồm email và các trường bắt buộc của User Model: first_name, last_name
# Bắt buộc phải có email* (để xác minh) và các trường name.
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'first_name', 'last_name']
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

ACCOUNT_UNIQUE_EMAIL = True

# ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# 4. Các thiết lập khác
# Tự động đăng nhập người dùng mới thay vì yêu cầu xác nhận email
# ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Khuyến nghị: Bắt buộc xác minh email

# Cấu hình Custom Adapters
ACCOUNT_ADAPTER = 'accounts.adapter.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapter.CustomSocialAccountAdapter' # Quan trọng

# Kích hoạt lưu trữ S3/Minio mặc định
DEFAULT_FILE_STORAGE = 'minio_storage.storage.MinioMediaStorage'

# Cấu hình Minio
MINIO_STORAGE_ENDPOINT = config('MINIO_ENDPOINT', default='minio:9000') # Dùng tên service trong Docker
MINIO_STORAGE_ACCESS_KEY = config('MINIO_ROOT_USER', default='root')
MINIO_STORAGE_SECRET_KEY = config('MINIO_ROOT_PASSWORD')
MINIO_STORAGE_MEDIA_BUCKET_NAME = config('MINIO_BUCKET_NAME', default='document-storage')

# Minio không yêu cầu HTTPS trong môi trường phát triển Docker
MINIO_STORAGE_USE_HTTPS = False

# Minio Public Endpoint (dùng khi tạo URL cho người dùng tải xuống)
MINIO_STORAGE_MEDIA_URL = config('MINIO_PUBLIC_ENDPOINT', default='http://localhost:9000') + '/' + MINIO_STORAGE_MEDIA_BUCKET_NAME + '/'

# Bật/Tắt tính năng tạo Bucket tự động (phục vụ dev)
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True

# Cấu hình bảo mật: Sử dụng Signed URLs cho Download (quan trọng theo blueprint)
# Điều này đảm bảo rằng không ai có thể truy cập file nếu không có quyền
MINIO_STORAGE_USE_PRESIGNED_URLS = True # Bật tính năng tạo Signed URL cho file
# Hết hạn của Signed URL (ví dụ: 5 phút)
MINIO_STORAGE_PRESIGNED_URLS_EXPIRY = 300

# STATIC files (tùy chọn, không bắt buộc cho project này)
# STATICFILES_STORAGE = 'minio_storage.storage.MinioStaticStorage'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        # Log của Django
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        # Log của ứng dụng
        'documents': {
            'handlers': ['console'],
            'level': 'DEBUG', # Dùng DEBUG cho môi trường dev, INFO cho prod
            'propagate': True,
        },
        # Log của Celery (quan trọng)
        'celery': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
